version: '3.7'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 app:app
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
    links:
      - mongodb
  mongodb:
    image: mongo:4
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodbdata:
    driver: local